given_name: "Andrey"
family_name: "Okonetchnikov"
name: "Andrey Okonetchnikov"
email: "andrey@okonet.ru"
description: "Andrey Okonetchnikov &mdash; Front-End Engineer"
keywords: "Andrey Okonetchnikov, Andrey, Andrew, Andrej, Okonetchnikov, Okonechnikov, Okonetschnikow, front, front-end, front-end architect, web, web development, engineer, client-side, developer, designer, User Interface, User Experience, Ajax, JavaScript, HTML, CSS, HTML5, CSS3, front-end, developer, designer, user interface, experience, ui, ux, architect, personal, resume, Compass, SASS"
company: "okonet.ru"
photo: "http://www.gravatar.com/avatar/0c6c742c4c56a2d837a5d6eb7195a8c6.jpg"
