given_name: "Andrey"
family_name: "Okonetchnikov"
name: "Andrey Okonetchnikov"
phone: "+43 681 10941323"
email: "andrey@okonet.ru"
role: "Front-End Engineer"
description: "Andrey Okonetchnikov &mdash; Front-End Engineer"
keywords: "Andrey Okonetchnikov, Andrey, Andrew, Andrej, Okonetchnikov, Okonechnikov, Okonetschnikow, front, front-end, front-end architect, web, web development, engineer, client-side, developer, designer, User Interface, User Experience, Ajax, JavaScript, HTML, CSS, HTML5, CSS3, front-end, developer, designer, user interface, experience, ui, ux, architect, personal, resume, Compass, SASS"
company: "okonet.ru"
photo: "http://www.gravatar.com/avatar/0c6c742c4c56a2d837a5d6eb7195a8c6.jpg"
addr_location: "home"
addr_street: "Castellezgasse 14/9"
addr_locality: "Vienna"
addr_country: "Austria"
addr_postalcode: "1020"
gems:
  - 'jekyll-compass'
  - 'susy'
